version: '3'

vars:
  INGRESS_IP:        "{{ env `INGRESS_IP` }}"
  PROMETHEUS_HOST:   "{{ env `PROMETHEUS_HOST` }}"
  GRAFANA_HOST:      "{{ env `GRAFANA_HOST` }}"

tasks:

  # I had some issues with metallb and talos. Solved by adding this labels
  # source: https://github.com/siderolabs/talos/issues/10291
  prepare-metallb-namespace:
    desc: "Prepare MetalLB namespace"
    cmds:
      - kubectl label namespace metallb-system \
          pod-security.kubernetes.io/enforce=privileged \
          pod-security.kubernetes.io/audit=privileged \
          pod-security.kubernetes.io/warn=privileged --overwrite
  deploy:
    desc: "Deploy MetalLB, Ingress‑NGINX, and Monitoring Stack"
    cmds:
      - helm repo add metallb       https://metallb.github.io/metallb   || true
      - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx || true
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
      - helm repo update

      # MetalLB
      - kubectl create namespace metallb-system --dry-run=client -o yaml | kubectl apply -f -
      - INGRESS_IP={{.INGRESS_IP}} envsubst < charts/metallb-pool.yaml | kubectl apply -f -
      - helm upgrade --install metallb metallb/metallb --namespace metallb-system

      # Ingress‑NGINX
      - kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -
      - INGRESS_IP={{.INGRESS_IP}} envsubst < charts/ingress-nginx-values.yaml | \
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx

      # Monitoring stack
      - kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      - |
        PROMETHEUS_HOST={{.PROMETHEUS_HOST}} \
        GRAFANA_HOST={{.GRAFANA_HOST}} \
          envsubst < charts/kube-prometheus-stack-values.yaml > /tmp/monitoring-values.yaml
      - helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
          --namespace monitoring -f /tmp/monitoring-values.yaml

  teardown:
    desc: "Tear down Monitoring Stack, Ingress, and MetalLB"
    cmds:
      - helm uninstall monitoring   --namespace monitoring   || true
      - kubectl delete namespace monitoring                  || true
      - helm uninstall ingress-nginx --namespace ingress-nginx || true
      - kubectl delete namespace ingress-nginx                || true
      - helm uninstall metallb      --namespace metallb-system || true
      - kubectl delete namespace metallb-system               || true
