# values.yaml

grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - ${GRAFANA_HOST}
    paths:
      - /

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - ${PROMETHEUS_HOST}
    paths:
      - /
  # Lets add extra scrape config for proxmox
  # make sure the proxmox pve collector is installed
  prometheusSpec:
    additionalScrapeConfigs: |-
      - job_name: "proxmox"
        scrape_interval: 30s
        metrics_path: "/pve"
        params:
          target: ["proxmox.home"]
        static_configs:
          # - targets: ["prometheus-exporter.home:9221"]
          - targets: ["prometheus-exporter.monitoring.svc.cluster.local:9221"]

serviceMonitor:
  enabled: true
  interval: 60s
  additionalLabels:
    release: monitoring
